// navigation-links.ts (shared location)
import { ComponentType } from 'src/shared/interfaces/component-type';

export const NAV_LINKS: ComponentType[] = [
    {
        name: 'Home',
        description: 'Welcome to my personal portfolio website. Here you can find information about my work, skills, and projects.',
        icon: 'bi bi-house-fill',
        route: '/home',
        isActive: true,
        order: 1,
        developerOnly: false,
        isExternal: false,
        externalUrl: '',
        tags: ['portfolio', 'home', 'introduction'],
        additionalInfo: 'This is the landing page of my portfolio where I introduce myself and my work.',
        isHidden: false,
        isDeprecated: false,
        lastUpdated: new Date('2025-08-06'),
        version: '1.0.0',
        relatedComponents: ['About', 'Projects', 'Contact'],
        documentationUrl: '',
        isExperimental: false,
        isFeatured: true,
        isBeta: false,
        isStable: true
    },
    {
        name: 'About Me',
        description: 'Learn more about my background, skills, and experience.',
        route: '/more-info/about-me',
        icon: 'bi bi-person-fill',
        isActive: true,
        order: 2,
        developerOnly: false,
        isExternal: false,
        externalUrl: '',
        tags: ['portfolio', 'home', 'introduction'],
        additionalInfo: 'This section provides an overview of my professional background, skills, and experience.',
        isHidden: false,
        isDeprecated: false,
        lastUpdated: new Date('2025-08-06'),
        version: '1.0.0',
        relatedComponents: ['Home', 'Projects', 'Contact'],
        documentationUrl: '',
        isExperimental: false,
        isFeatured: true,
        isBeta: false,
        isStable: true
    },
    {
        name: 'Resume',
        description: 'View my professional resume',
        route: '/more-info/resume',
        icon: 'bi bi-briefcase-fill',
        isActive: false,
        order: 3,
        developerOnly: true,
        isExternal: false,
        externalUrl: '',
        tags: ['portfolio', 'home', 'introduction'],
        additionalInfo: 'This is the landing page of my portfolio where I introduce myself and my work.',
        isHidden: true,
        isDeprecated: false,
        lastUpdated: new Date('2025-08-06'),
        version: '1.0.0',
        relatedComponents: ['About', 'Projects', 'Contact'],
        documentationUrl: '',
        isExperimental: false,
        isFeatured: false,
        isBeta: false,
        isStable: false
    },
    {
        name: 'Projects',
        description: 'Explore my projects and contributions to various open-source initiatives.',
        route: '/projects',
        icon: 'bi bi-collection-fill',
        isActive: false,
        order: 4,
        developerOnly: false,
        isExternal: false,
        externalUrl: '',
        tags: ['portfolio', 'projects', 'work'],
        additionalInfo: 'This section showcases my projects, including descriptions, technologies used, and links to repositories.',
        isHidden: false,
        isDeprecated: false,
        lastUpdated: new Date('2025-08-06'),
        version: '1.0.0',
        relatedComponents: ['Home', 'About', 'Contact'],
        documentationUrl: '',
        isExperimental: false,
        isFeatured: true,
        isBeta: false,
        isStable: true
    },
    {
        name: 'Contact',
        description: 'Get in touch with me for collaborations or inquiries.',
        route: '/more-info/contact',
        icon: 'bi bi-envelope-fill',
        isActive: true,
        order: 5,
        developerOnly: false,
        isExternal: false,
        externalUrl: '',
        tags: ['portfolio', 'contact', 'inquiries'],
        additionalInfo: 'This section provides a contact form for visitors to reach out to me directly.',
        isHidden: false,
        isDeprecated: false,
        lastUpdated: new Date('2025-08-06'),
        version: '1.0.0',
        relatedComponents: ['Home', 'About', 'Projects'],
        documentationUrl: '',
        isExperimental: false,
        isFeatured: true,
        isBeta: false,
        isStable: true
    },
    {
        name: 'Blog',
        description: 'Read my latest articles and insights on web development and technology.',
        route: '',
        icon: 'bi bi-journal-text',
        isActive: true,
        order: 6,
        developerOnly: false,
        isExternal: true,
        externalUrl: 'https://blog.mayankahuja.in',
        tags: ['portfolio', 'blog', 'articles'],
        additionalInfo: 'This section features my blog posts, where I share insights, tutorials, and experiences in web development.',
        isHidden: false,
        isDeprecated: false,
        lastUpdated: new Date('2025-08-06'),
        version: '1.0.0',
        relatedComponents: ['Home', 'About', 'Contact'],
        documentationUrl: '',
        isExperimental: false,
        isFeatured: true,
        isBeta: false,
        isStable: false
    }
    

    // ...other links
];